import { Roadmap, LearnerProfile } from '../types';

export const exportRoadmapToMarkdown = (roadmap: Roadmap, profile: LearnerProfile): string => {
  let md = `# RouteMind Personalized Study Roadmap: ${roadmap.targetRoleTitle}\n\n`;
  md += `**Learner Name:** ${profile.name}\n`;
  md += `**Skill Baseline Level:** ${profile.currentSkillLevel}\n`;
  md += `**Pace:** ${profile.hoursPerWeek} hours/week\n`;
  md += `**Estimated Duration:** ${roadmap.estimatedWeeks} weeks (${roadmap.totalHours} total hours)\n`;
  md += `**Overall Progress:** ${roadmap.overallCompletionPercentage}%\n`;
  md += `**Generated Date:** ${new Date(roadmap.createdAt).toLocaleDateString()}\n\n`;
  md += `---\n\n`;

  roadmap.phases.forEach((phase) => {
    md += `## ${phase.title}\n`;
    md += `*${phase.description}*\n\n`;

    phase.milestones.forEach((m, idx) => {
      const statusSymbol =
        m.status === 'Completed'
          ? '[x]'
          : m.status === 'In-Progress'
          ? '[/]'
          : '[ ]';

      md += `### ${statusSymbol} ${idx + 1}. ${m.title}\n`;
      md += `- **Provider:** ${m.course.provider}\n`;
      md += `- **Duration:** ~${m.course.durationHours} hours (${m.estimatedWeeks} weeks)\n`;
      md += `- **Cost & Rating:** ${m.course.cost} | ⭐ ${m.course.rating}/5.0\n`;
      md += `- **Skills Gained:** ${m.skillsGained.join(', ')}\n`;
      md += `- **Resource Link:** [${m.course.title}](${m.course.url})\n`;
      md += `- **Why Recommended (XAI):** ${m.rationales.skillGapAddressed}\n`;

      if (m.capstoneProject) {
        md += `\n  > 🛠️ **Capstone Project:** ${m.capstoneProject.title}\n`;
        md += `  > ${m.capstoneProject.description}\n`;
      }
      md += `\n`;
    });
  });

  md += `---\n*Generated by RouteMind Adaptive Learning Path Intelligence*\n`;
  return md;
};

export const exportRoadmapToJSON = (roadmap: Roadmap, profile: LearnerProfile): string => {
  return JSON.stringify(
    {
      exportVersion: '1.0',
      exportedAt: new Date().toISOString(),
      profile,
      roadmap,
    },
    null,
    2
  );
};

export const exportRoadmapToICalendar = (roadmap: Roadmap, profile: LearnerProfile): string => {
  let ics = `BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//RouteMind Learning Path Recommender//EN\nCALSCALE:GREGORIAN\nMETHOD:PUBLISH\nX-WR-CALNAME:RouteMind Roadmap - ${roadmap.targetRoleTitle}\n`;

  const startDate = new Date();

  roadmap.phases.forEach((phase) => {
    phase.milestones.forEach((m) => {
      const startIso = startDate.toISOString().replace(/-|:|\.\d+/g, '');
      const endDate = new Date(startDate.getTime() + m.estimatedWeeks * 7 * 24 * 60 * 60 * 1000);
      const endIso = endDate.toISOString().replace(/-|:|\.\d+/g, '');

      ics += `BEGIN:VEVENT\n`;
      ics += `UID:routemind-${m.id}@routemind.ai\n`;
      ics += `DTSTAMP:${new Date().toISOString().replace(/-|:|\.\d+/g, '')}\n`;
      ics += `DTSTART:${startIso}\n`;
      ics += `DTEND:${endIso}\n`;
      ics += `SUMMARY:📚 RouteMind Study: ${m.title}\n`;
      ics += `DESCRIPTION:${m.description.replace(/\n/g, ' ')}\\n\\nProvider: ${m.course.provider}\\nURL: ${m.course.url}\n`;
      ics += `LOCATION:${m.course.url}\n`;
      ics += `STATUS:CONFIRMED\n`;
      ics += `END:VEVENT\n`;

      // Advance start date for next milestone
      startDate.setTime(endDate.getTime());
    });
  });

  ics += `END:VCALENDAR\n`;
  return ics;
};

export const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
